### ISSUE TITLE
Question: Add playbook/tasks to install cowsay example app?

### ISSUE THREAD

**Issue by benblasco** [shaneboulden/fapolicyd-config#1]
Would it be worth adding a playbook to install cowsay as well?

e.g.
```
  tasks:
    - name: Grab the cowsay application
      ansible.builtin.unarchive:
        src: https://github.com/Code-Hex/Neo-cowsay/releases/download/v2.0.4/cowsay_2.0.4_Linux_x86_64.tar.gz
        dest: /usr/local/bin
        remote_src: yes
```
Alternatively it could be added to site.yml depending on how you use this repo.
